@startuml
'https://plantuml.com/sequence-diagram

autonumber

矩阵 -> 矩阵 : 初始化
loop 如果游戏未结束
    矩阵 -> 当前玩家: 摸牌
    return ActionResult
    alt ActionResult.code==NoAction
        矩阵 -> 矩阵 : 结束步骤
    end
    alt ActionResult.code==ZiMo
        矩阵 -> 矩阵 : 结账
    end
    alt ActionResult.code==MingGang
        矩阵 -> 矩阵 : 结账
    end
    alt ActionResult.code==AnGang
        矩阵 -> 矩阵 : 结账
    end
    alt ActionResult.code==ChuPai
        loop
            矩阵->矩阵:玩家看牌
        end
    end
end

@enduml