@startuml
'https://plantuml.com/sequence-diagram

autonumber

矩阵 -> 矩阵 : 初始化
loop 如果游戏未结束
    矩阵 -> 当前玩家: 摸牌
    return 当前牌
    loop 其它玩家
        矩阵 -> 其它玩家: 胡牌(当前牌)
    end
    alt 如果没人胡牌
        loop 其它玩家
            矩阵 -> 其它玩家: 碰牌(当前牌)
        end
        loop 其它玩家
            矩阵 -> 其它玩家: 杠牌(当前牌)
        end
    end
    矩阵 -> 矩阵 : 结账
    矩阵 -> 矩阵 : 当前玩家移动到下一个
end

@enduml